package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:40:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idEmpresa;
     private String nombre;
     private String oficinas;
     private Integer fundacion;
     private Integer numEmpleado;
     private Integer contacto;
     private String presidente;
     private Set vacantes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Empresa(int idEmpresa, String nombre, String oficinas, Integer fundacion, Integer numEmpleado, Integer contacto, String presidente, Set vacantes) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.oficinas = oficinas;
       this.fundacion = fundacion;
       this.numEmpleado = numEmpleado;
       this.contacto = contacto;
       this.presidente = presidente;
       this.vacantes = vacantes;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(String oficinas) {
        this.oficinas = oficinas;
    }
    public Integer getFundacion() {
        return this.fundacion;
    }
    
    public void setFundacion(Integer fundacion) {
        this.fundacion = fundacion;
    }
    public Integer getNumEmpleado() {
        return this.numEmpleado;
    }
    
    public void setNumEmpleado(Integer numEmpleado) {
        this.numEmpleado = numEmpleado;
    }
    public Integer getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Integer contacto) {
        this.contacto = contacto;
    }
    public String getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }
    public Set getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Set vacantes) {
        this.vacantes = vacantes;
    }




}


