package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:40:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExperienciaLaboralId generated by hbm2java
 */
public class ExperienciaLaboralId  implements java.io.Serializable {


     private String empresa;
     private String cargo;
     private Date inicioPeriodo;
     private Date finPeriodo;

    public ExperienciaLaboralId() {
    }

    public ExperienciaLaboralId(String empresa, String cargo, Date inicioPeriodo, Date finPeriodo) {
       this.empresa = empresa;
       this.cargo = cargo;
       this.inicioPeriodo = inicioPeriodo;
       this.finPeriodo = finPeriodo;
    }
   
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getInicioPeriodo() {
        return this.inicioPeriodo;
    }
    
    public void setInicioPeriodo(Date inicioPeriodo) {
        this.inicioPeriodo = inicioPeriodo;
    }
    public Date getFinPeriodo() {
        return this.finPeriodo;
    }
    
    public void setFinPeriodo(Date finPeriodo) {
        this.finPeriodo = finPeriodo;
    }




}


