package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:40:38 PM by Hibernate Tools 4.3.1



/**
 * FormacionAcademica generated by hbm2java
 */
public class FormacionAcademica  implements java.io.Serializable {


     private FormacionAcademicaId id;
     private Integer fkIdProfesionista;

    public FormacionAcademica() {
    }

	
    public FormacionAcademica(FormacionAcademicaId id) {
        this.id = id;
    }
    public FormacionAcademica(FormacionAcademicaId id, Integer fkIdProfesionista) {
       this.id = id;
       this.fkIdProfesionista = fkIdProfesionista;
    }
   
    public FormacionAcademicaId getId() {
        return this.id;
    }
    
    public void setId(FormacionAcademicaId id) {
        this.id = id;
    }
    public Integer getFkIdProfesionista() {
        return this.fkIdProfesionista;
    }
    
    public void setFkIdProfesionista(Integer fkIdProfesionista) {
        this.fkIdProfesionista = fkIdProfesionista;
    }




}


