package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:40:38 PM by Hibernate Tools 4.3.1



/**
 * PostularId generated by hbm2java
 */
public class PostularId  implements java.io.Serializable {


     private Integer fkProfesionista;
     private Integer fkVacante;

    public PostularId() {
    }

    public PostularId(Integer fkProfesionista, Integer fkVacante) {
       this.fkProfesionista = fkProfesionista;
       this.fkVacante = fkVacante;
    }
   
    public Integer getFkProfesionista() {
        return this.fkProfesionista;
    }
    
    public void setFkProfesionista(Integer fkProfesionista) {
        this.fkProfesionista = fkProfesionista;
    }
    public Integer getFkVacante() {
        return this.fkVacante;
    }
    
    public void setFkVacante(Integer fkVacante) {
        this.fkVacante = fkVacante;
    }




}


