package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:40:38 PM by Hibernate Tools 4.3.1



/**
 * Postular generated by hbm2java
 */
public class Postular  implements java.io.Serializable {


     private PostularId id;
     private Vacante vacante;

    public Postular() {
    }

	
    public Postular(PostularId id) {
        this.id = id;
    }
    public Postular(PostularId id, Vacante vacante) {
       this.id = id;
       this.vacante = vacante;
    }
   
    public PostularId getId() {
        return this.id;
    }
    
    public void setId(PostularId id) {
        this.id = id;
    }
    public Vacante getVacante() {
        return this.vacante;
    }
    
    public void setVacante(Vacante vacante) {
        this.vacante = vacante;
    }




}


